"""
NER-SAFE Centralized Dataset
MDoNER Disaster Management Platform - SIH 2026 PS 26001
Covers North Eastern Region (NER) India states, districts, infrastructure, weather, and historical landslide data.
"""

NER_STATES = [
    "Assam", "Arunachal Pradesh", "Manipur", "Meghalaya", 
    "Mizoram", "Nagaland", "Sikkim", "Tripura"
]

LOCATIONS = [
    {
        "id": "loc-aizawl-01",
        "name": "Aizawl District (Ridge Zone)",
        "state": "Mizoram",
        "district": "Aizawl",
        "lat": 23.7271,
        "lng": 92.7176,
        "riskLevel": "CRITICAL",
        "probability": 87,
        "rainfall24h": 165,
        "rainfall1h": 18,
        "rainfall6h": 72,
        "soilMoisture": 82,
        "slope": 37,
        "elevation": 1132,
        "historicalRisk": "High",
        "satelliteRisk": 74,
        "nearbyVillages": 6,
        "nearbyRoads": ["NH-6", "SH-3"],
        "nearbyHospitals": 2,
        "populationAffected": 14200,
        "recommendedAction": "Immediate slope evacuation order and deployment of SDRF team to NH-6 junction."
    },
    {
        "id": "loc-kohima-02",
        "name": "Kohima South Slope",
        "state": "Nagaland",
        "district": "Kohima",
        "lat": 25.6751,
        "lng": 94.1086,
        "riskLevel": "HIGH",
        "probability": 76,
        "rainfall24h": 140,
        "rainfall1h": 14,
        "rainfall6h": 58,
        "soilMoisture": 76,
        "slope": 32,
        "elevation": 1444,
        "historicalRisk": "High",
        "satelliteRisk": 68,
        "nearbyVillages": 4,
        "nearbyRoads": ["NH-2"],
        "nearbyHospitals": 1,
        "populationAffected": 9800,
        "recommendedAction": "Issue heavy rainfall advisory and position earthmovers on NH-2 pass."
    },
    {
        "id": "loc-shillong-03",
        "name": "Shillong Bypass Pass",
        "state": "Meghalaya",
        "district": "East Khasi Hills",
        "lat": 25.5788,
        "lng": 91.8933,
        "riskLevel": "HIGH",
        "probability": 71,
        "rainfall24h": 185,
        "rainfall1h": 22,
        "rainfall6h": 90,
        "soilMoisture": 88,
        "slope": 29,
        "elevation": 1525,
        "historicalRisk": "Moderate",
        "satelliteRisk": 62,
        "nearbyVillages": 8,
        "nearbyRoads": ["NH-6", "GS Road"],
        "nearbyHospitals": 3,
        "populationAffected": 21500,
        "recommendedAction": "Restrict heavy vehicular movement along Shillong Bypass."
    },
    {
        "id": "loc-gangtok-04",
        "name": "Gangtok North Ridge (NH-10 Corridor)",
        "state": "Sikkim",
        "district": "East Sikkim",
        "lat": 27.3389,
        "lng": 88.6065,
        "riskLevel": "CRITICAL",
        "probability": 84,
        "rainfall24h": 155,
        "rainfall1h": 16,
        "rainfall6h": 68,
        "soilMoisture": 85,
        "slope": 41,
        "elevation": 1650,
        "historicalRisk": "High",
        "satelliteRisk": 79,
        "nearbyVillages": 5,
        "nearbyRoads": ["NH-10"],
        "nearbyHospitals": 2,
        "populationAffected": 11200,
        "recommendedAction": "Maintain high alert along NH-10 lifelines; inspect retaining walls."
    },
    {
        "id": "loc-itanagar-05",
        "name": "Itanagar Papum Pare Hill",
        "state": "Arunachal Pradesh",
        "district": "Papum Pare",
        "lat": 27.0844,
        "lng": 93.6053,
        "riskLevel": "MODERATE",
        "probability": 52,
        "rainfall24h": 92,
        "rainfall1h": 8,
        "rainfall6h": 34,
        "soilMoisture": 61,
        "slope": 26,
        "elevation": 750,
        "historicalRisk": "Moderate",
        "satelliteRisk": 45,
        "nearbyVillages": 3,
        "nearbyRoads": ["NH-415"],
        "nearbyHospitals": 1,
        "populationAffected": 6400,
        "recommendedAction": "Routine field sensor monitoring and drainage check."
    },
    {
        "id": "loc-imphal-06",
        "name": "Imphal-Jiribam NH-37 Corridor",
        "state": "Manipur",
        "district": "Noney",
        "lat": 24.817,
        "lng": 93.655,
        "riskLevel": "HIGH",
        "probability": 79,
        "rainfall24h": 148,
        "rainfall1h": 15,
        "rainfall6h": 61,
        "soilMoisture": 79,
        "slope": 35,
        "elevation": 920,
        "historicalRisk": "High",
        "satelliteRisk": 72,
        "nearbyVillages": 7,
        "nearbyRoads": ["NH-37"],
        "nearbyHospitals": 1,
        "populationAffected": 8700,
        "recommendedAction": "Deploy quick reaction team for landslide prone slopes near Noney railway portal."
    },
    {
        "id": "loc-silchar-07",
        "name": "Dima Hasao Haflong Valley",
        "state": "Assam",
        "district": "Dima Hasao",
        "lat": 25.1764,
        "lng": 93.0159,
        "riskLevel": "CRITICAL",
        "probability": 89,
        "rainfall24h": 210,
        "rainfall1h": 24,
        "rainfall6h": 105,
        "soilMoisture": 91,
        "slope": 34,
        "elevation": 512,
        "historicalRisk": "High",
        "satelliteRisk": 85,
        "nearbyVillages": 11,
        "nearbyRoads": ["NH-27", "Lumding Railway Corridor"],
        "nearbyHospitals": 2,
        "populationAffected": 18900,
        "recommendedAction": "Activate district disaster mitigation protocol; inspect Lumding-Silchar rail embankments."
    },
    {
        "id": "loc-agartala-08",
        "name": "Jampui Hills Corridor",
        "state": "Tripura",
        "district": "North Tripura",
        "lat": 23.9167,
        "lng": 92.2833,
        "riskLevel": "LOW",
        "probability": 28,
        "rainfall24h": 42,
        "rainfall1h": 4,
        "rainfall6h": 14,
        "soilMoisture": 44,
        "slope": 19,
        "elevation": 620,
        "historicalRisk": "Low",
        "satelliteRisk": 22,
        "nearbyVillages": 3,
        "nearbyRoads": ["SH-8"],
        "nearbyHospitals": 1,
        "populationAffected": 3100,
        "recommendedAction": "Standard green status; normal monitoring."
    }
]

INFRASTRUCTURE_ASSETS = [
    {
        "id": "infra-01",
        "name": "National Highway NH-6 (Silchar-Aizawl Link)",
        "type": "Highway",
        "riskLevel": "CRITICAL",
        "status": "High Blockage Risk",
        "location": "Aizawl / Dima Hasao border",
        "affectedPopulation": 35000,
        "distanceToRiskZoneKm": 0.4,
        "nearestHospital": "Aizawl Civil Hospital (7.2 km)",
        "lat": 23.75,
        "lng": 92.73
    },
    {
        "id": "infra-02",
        "name": "Lumding-Silchar Mountain Railway",
        "type": "Rail Transit",
        "riskLevel": "CRITICAL",
        "status": "Track Subsidence Alert",
        "location": "Haflong Hill Cut",
        "affectedPopulation": 50000,
        "distanceToRiskZoneKm": 0.2,
        "nearestHospital": "Haflong Civil Hospital (4.1 km)",
        "lat": 25.18,
        "lng": 93.02
    },
    {
        "id": "infra-03",
        "name": "NH-2 Kohima-Imphal Highway",
        "type": "Highway",
        "riskLevel": "HIGH",
        "status": "Cracks Reported on Shoulder",
        "location": "Kohima South Bypass",
        "affectedPopulation": 22000,
        "distanceToRiskZoneKm": 0.8,
        "nearestHospital": "Naga Hospital Authority Kohima (5.3 km)",
        "lat": 25.66,
        "lng": 94.11
    },
    {
        "id": "infra-04",
        "name": "NH-10 Siliguri-Gangtok Expressway",
        "type": "Highway",
        "riskLevel": "CRITICAL",
        "status": "Shooting Stones Reported",
        "location": "Singtam Cut",
        "affectedPopulation": 18000,
        "distanceToRiskZoneKm": 0.3,
        "nearestHospital": "STNM Hospital Gangtok (11.0 km)",
        "lat": 27.24,
        "lng": 88.50
    },
    {
        "id": "infra-05",
        "name": "Tuirial Bridge (SH-3)",
        "type": "Bridge",
        "riskLevel": "MODERATE",
        "status": "Under Structural Monitoring",
        "location": "Aizawl East",
        "affectedPopulation": 8500,
        "distanceToRiskZoneKm": 1.9,
        "nearestHospital": "Greenwood Hospital Aizawl (12.4 km)",
        "lat": 23.70,
        "lng": 92.80
    }
]

HISTORICAL_ANALYTICS = {
    "yearlyTrends": [
        {"year": 2021, "incidents": 142, "avgRainfall": 2150, "fatalities": 14, "highRiskEvents": 18},
        {"year": 2022, "incidents": 189, "avgRainfall": 2480, "fatalities": 22, "highRiskEvents": 29},
        {"year": 2023, "incidents": 215, "avgRainfall": 2610, "fatalities": 19, "highRiskEvents": 34},
        {"year": 2024, "incidents": 278, "avgRainfall": 2890, "fatalities": 31, "highRiskEvents": 48},
        {"year": 2025, "incidents": 310, "avgRainfall": 3050, "fatalities": 28, "highRiskEvents": 56}
    ],
    "stateDistribution": [
        {"state": "Assam (Hilly Districts)", "incidents": 84, "percentage": 27},
        {"state": "Mizoram", "incidents": 68, "percentage": 22},
        {"state": "Meghalaya", "incidents": 52, "percentage": 17},
        {"state": "Sikkim", "incidents": 41, "percentage": 13},
        {"state": "Nagaland", "incidents": 32, "percentage": 10},
        {"state": "Arunachal Pradesh", "incidents": 21, "percentage": 7},
        {"state": "Manipur", "incidents": 12, "percentage": 4}
    ]
}

MULTILINGUAL_TRANSLATIONS = {
    "English": {
        "title": "NER-SAFE Command Center",
        "tagline": "North Eastern Region – Smart AI-based Forecasting & Emergency System",
        "critical_alert": "Critical Landslide Danger Detected! Avoid NH-6 & evacuation zones.",
        "high_alert": "High Landslide Risk Warning. Slope monitoring active.",
        "moderate_alert": "Moderate landslide risk. Stay alert during heavy rain.",
        "low_alert": "Low landslide risk. Normal conditions.",
        "rainfall_label": "24h Rainfall",
        "moisture_label": "Soil Saturation",
        "probability_label": "Landslide Probability",
        "recommended_action": "Recommended Response Action",
        "notify_authorities": "Notify Authorities",
        "notify_community": "Broadcast Community Warning",
        "run_demo": "RUN DEMO SCENARIO"
    },
    "Hindi": {
        "title": "NER-SAFE कमान केंद्र",
        "tagline": "उत्तर पूर्वी क्षेत्र – स्मार्ट एआई आधारित भूस्खलन पूर्वानुमान और आपातकालीन प्रणाली",
        "critical_alert": "भूस्खलन का गंभीर खतरा पाया गया है! राष्ट्रीय राजमार्ग-6 से बचें और निकासी क्षेत्र में अलर्ट रहें।",
        "high_alert": "उच्च भूस्खलन जोखिम चेतावनी। ढलान निगरानी सक्रिय।",
        "moderate_alert": "मध्यम भूस्खलन जोखिम। भारी बारिश के दौरान सतर्क रहें।",
        "low_alert": "कम भूस्खलन जोखिम। सामान्य स्थिति।",
        "rainfall_label": "24 घंटे बारिश",
        "moisture_label": "मिट्टी की नमी",
        "probability_label": "भूस्खलन संभावना",
        "recommended_action": "अनुशंसित प्रतिक्रिया कार्रवाई",
        "notify_authorities": "अधिकारियों को सूचित करें",
        "notify_community": "समुदाय चेतावनी जारी करें",
        "run_demo": "डेमो परिदृश्य चलाएं"
    },
    "Assamese": {
        "title": "NER-SAFE নিৰ্দেশনা কেন্দ্ৰ",
        "tagline": "উত্তৰ-পূৰ্বাঞ্চল – স্মাৰ্ট এআই-ভিত্তিক ভূমিস্খলন পূৰ্বাভাস আৰু জৰুৰীকালীন ব্যৱস্থা",
        "critical_alert": "অতি সংকটজনক ভূমিস্খলনৰ সঁকিয়নী! ৰাষ্ট্ৰীয় ঘাইপথ-৬ ৰ পৰা আঁতৰি থাকক।",
        "high_alert": "উচ্চ ভূমিস্খলনৰ আশংকা। ঢালৰ নিৰীক্ষণ অব্যাহত।",
        "moderate_alert": "মধ্যমীয়া ভূমিস্খলনৰ সম্ভাৱনা।",
        "low_alert": "স্বাভাৱিক অৱস্থা।",
        "rainfall_label": "২৪ ঘণ্টাৰ বৰষুণ",
        "moisture_label": "মাটিৰ আৰ্দ্ৰতা",
        "probability_label": " ভূমিস্খলনৰ সম্ভাৱনা",
        "recommended_action": "প্ৰস্তাৱিত পদক্ষেপ",
        "notify_authorities": "কর্তৃপক্ষক অৱগত কৰক",
        "notify_community": "ৰাইজক সতৰ্ক কৰক",
        "run_demo": "ডেমো আৰম্ভ কৰক"
    },
    "Bengali": {
        "title": "NER-SAFE কমান্ড সেন্টার",
        "tagline": "উত্তর-পূর্বাঞ্চল – স্মার্ট এআই ভিত্তিক ভূমিধস পূর্বাভাস ও জরুরি ব্যবস্থা",
        "critical_alert": "মারাত্মক ভূমিধসের ঝুঁকি ধরা পড়েছে! জাতীয় সড়ক-৬ সংলগ্ন এলাকা এড়িয়ে চলুন।",
        "high_alert": "উচ্চ ভূমিধস সতর্কতা। পাহাড়ের ঢাল পর্যবেক্ষণ করা হচ্ছে।",
        "moderate_alert": "মাঝারি ভূমিধস ঝুঁকি। ভারী বৃষ্টিতে সতর্ক থাকুন।",
        "low_alert": "কম ঝুঁকি। স্বাভাবিক পরিস্থিতি।",
        "rainfall_label": "২৪ ঘণ্টার বৃষ্টিপাত",
        "moisture_label": "মাটির আর্দ্রতা",
        "probability_label": "ভূমিধসের সম্ভাবনা",
        "recommended_action": "সুপারিশকৃত জরুরি পদক্ষেপ",
        "notify_authorities": "কর্তৃপক্ষকে জানান",
        "notify_community": "জনগণকে সতর্ক করুন",
        "run_demo": "ডেমো চালান"
    },
    "Mizo": {
        "title": "NER-SAFE Aizawl Command Center",
        "tagline": "Mizo Rám Chhúng – AI hmanga Tlang Min Vengtu & Emergency System",
        "critical_alert": "Tlang min hlauhthawnawm tak a thleng mek! NH-6 leh tlang awihta zawn pumpelh rawh.",
        "high_alert": "Tlang min hlauhawm. Tlang pang enkawl active a ni.",
        "moderate_alert": "Fimkhur tawk a ngai. Ruah thawkulh zual hleiah fimkhur rawh.",
        "low_alert": "Hlauhawm loh. Pangngai a ni.",
        "rainfall_label": "Darkar 24 Ruah tui",
        "moisture_label": "Lung & Lei Hnawng",
        "probability_label": "Tlang Min Barakhaih",
        "recommended_action": "Tih tur rang tak",
        "notify_authorities": "Hotute Hriattir",
        "notify_community": "Khawtlang Hriattirna",
        "run_demo": "DEMO ENNA"
    },
    "Khasi": {
        "title": "NER-SAFE Command Center",
        "tagline": "Dong Mihngi – AI Forecasting bad Disaster Management System",
        "critical_alert": "Kynroh khyndew twep kaba shyrkhei! Phet sha kyndong na NH-6.",
        "high_alert": "Jingshyrkhei ba khraw jong ka twep khyndew.",
        "moderate_alert": "Phew ha kaba hap slap khraw.",
        "low_alert": "Long kaba jai-jai.",
        "rainfall_label": "Slap 24 Kynta",
        "moisture_label": "Jingsngem Khyndew",
        "probability_label": "Khyndew Twep Probability",
        "recommended_action": "Kam ban leh stet",
        "notify_authorities": "Pynip pyntip sha Sorkar",
        "notify_community": "Pyntip sha shnong",
        "run_demo": "LEH DEMO"
    },
    "Manipuri": {
        "title": "NER-SAFE Imphal Command Center",
        "tagline": "Nongpok Chingkhei Lamdam - AI-based Landslide Early Warning System",
        "critical_alert": "Chingda taiba yamna shina toure! NH-37 amadi Noney lammitthakta cheksinbiyu.",
        "high_alert": "Ching taibagi aksing yamna leire.",
        "moderate_alert": "Nong kanna taba matamda cheksinbiyu.",
        "low_alert": "Chamna leire.",
        "rainfall_label": "Pung 24 Nong taba",
        "moisture_label": "Leibakki a-sengba",
        "probability_label": "Ching taibagi chang",
        "recommended_action": "Tougadaba thabak",
        "notify_authorities": "Lainingthou Sorkarda Khanghanba",
        "notify_community": "Meyamda Cheksin-wa Haiba",
        "run_demo": "DEMO UTPA"
    }
}
